version: "3.8"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: web_nhahanglau
    environment:
      SA_PASSWORD: "Admin123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - backend

  app:
    image: ws-app
    container_name: web_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://db:1433;databaseName=WEB_NHAHANGLAU;encrypt=false;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: Admin123!
    networks:
      - backend

networks:
  backend:
